[package]
name = "tauri-plugin-bare-kit"
version = "0.1.0"
authors = ["You"]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-bare-kit"

[dependencies]
tauri = { version = "2.8.5" }
serde = "1.0"
thiserror = "2"

[target.'cfg(target_vendor = "apple")'.dependencies]
objc = "0.2.7"
block = "0.1.6"

[build-dependencies]
bindgen = "0.72.1"
tauri-plugin = { version = "2.4.0", features = ["build"] }
thiserror = "2"
