[package]
name = "tauri-plugin-bare-kit"
version = "0.1.0"
authors = ["You"]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/dist-js", "/guest-js", "/node_modules"]
links = "tauri-plugin-bare-kit"

[dependencies]
tauri = { version = "2.10.3" }
serde = "1.0"
thiserror = "2"
tokio = "1.48.0"
pathdiff = { version = "0.2.3", optional = true }
regex = { version = "1.12.3", features = ["std"], optional = true }

[target.'cfg(target_os = "android")'.dependencies]
base64 = "0.22.1"

[build-dependencies]
bindgen = "0.72.1"
tauri-plugin = { version = "2.5.4", features = ["build"] }

[features]
default = ["runtime"]
build = ["dep:pathdiff", "dep:regex"]
runtime = []
