name: bare-beam
options:
  bundleIdPrefix: me.tomasrav.bare-beam
  deploymentTarget:
    iOS: 14
fileGroups:
  - ../../src
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: bare-beam
      PRODUCT_BUNDLE_IDENTIFIER: me.tomasrav.bare-beam
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups:
        - app
targets:
  bare-beam_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Externals
      - path: bare-beam_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: bare-beam_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - arm64
          - metal
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 0.1.0
        CFBundleVersion: 0.1.0
    entitlements:
      path: bare-beam_iOS/bare-beam_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ARCHS:
          - arm64
        VALID_ARCHS: arm64
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited)
          $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION)
          $(SDKROOT)/usr/lib/swift
          $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
          $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited)
          $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION)
          $(SDKROOT)/usr/lib/swift
          $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
          $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups:
        - app
    dependencies:
      - framework: libapp.a
        embed: false
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/BareKit.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-buffer.3.6.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-type.1.1.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-inspect.3.1.4.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-os.3.9.1.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-url.2.4.3.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/sodium-native.5.1.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/udx-native.1.19.2.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-fs.4.7.1.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-abort.2.0.13.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-hrtime.2.1.1.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-signals.4.2.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-pipe.4.1.5.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-tty.5.1.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-stdio.1.0.2.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-os.3.9.3.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-buffer.3.6.1.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-url.2.4.5.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-fs.4.7.2.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-pipe.4.2.3.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-structured-clone.1.6.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-dns.2.1.4.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-tcp.2.5.4.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-subprocess.6.1.0.framework
      - framework: $(PROJECT_DIR)/Externals/$(NATIVE_ARCH)/$(CONFIGURATION)/bare-module-lexer.1.6.3.framework
    preBuildScripts:
      - script: npm run -- tauri ios xcode-script -v --platform
          ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?}
          --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}"
          --header-search-paths "${HEADER_SEARCH_PATHS:?}"
          --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}"
          --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a
