name: app
options:
  bundleIdPrefix: sh.quince.bare-beam
  deploymentTarget:
    iOS: 14
fileGroups:
  - ../../src
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: bare-beam
      PRODUCT_BUNDLE_IDENTIFIER: sh.quince.bare-beam
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups:
        - app
targets:
  app_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Assets.xcassets
      - path: Externals
      - path: app_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: app_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - arm64
          - metal
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 0.1.0
        CFBundleVersion: 0.1.0
    entitlements:
      path: app_iOS/app_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ARCHS:
          - arm64
        VALID_ARCHS: arm64
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited)
          $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION)
          $(SDKROOT)/usr/lib/swift
          $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
          $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
          $(PROJECT_DIR)/Frameworks
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited)
          $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION)
          $(SDKROOT)/usr/lib/swift
          $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)
          $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
          $(PROJECT_DIR)/Frameworks
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups:
        - app
    dependencies:
      - framework: libapp.a
        embed: false
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
      - framework: $(PROJECT_DIR)/Frameworks/BareKit.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-buffer.3.4.2.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-fs.4.5.2.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-hrtime.2.1.1.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-module-lexer.1.4.7.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-os.3.6.2.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-pipe.4.1.0.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-signals.4.2.0.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-subprocess.5.2.2.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-tty.5.0.3.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/bare-url.2.3.2.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/sodium-native.5.0.10.xcframework
      - framework: $(PROJECT_DIR)/Frameworks/udx-native.1.19.2.xcframework
    preBuildScripts:
      - script: npm run -- tauri ios xcode-script -v --platform
          ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?}
          --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}"
          --header-search-paths "${HEADER_SEARCH_PATHS:?}"
          --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}"
          --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a
