
[package]
name = 'tauri-plugin-bare-kit-tests'
version = '0.1.0'
description = 'A minimal Tauri app to test tauri-plugin-bare-kit'
authors = ['Tomas Ravinskas <tomas@tomasrav.me>']
license = 'Apache-2.0'
edition = '2021'

[lib]
name = 'tauri_plugin_bare_kit_tests_lib'
crate-type = ['staticlib', 'cdylib', 'rlib']

[build-dependencies]
tauri-build = { version = '2', features = [] }
tauri-plugin-bare-kit = { path = '../..', default-features = false, features = [
	'build',
] }

[dependencies]
tauri = { version = '2', features = [] }
tauri-plugin-opener = '2'
serde = { version = '1', features = ['derive'] }
serde_json = '1'
tauri-plugin-webdriver = '0.2'
tauri-plugin-bare-kit = { path = '../..' }
