[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-ping",
  "allow-bare-invalidate",
  "allow-bare-new",
  "allow-bare-start",
  "allow-bare-read",
  "allow-bare-write",
  "allow-bare-update",
  "allow-bare-suspend",
  "allow-bare-resume",
  "allow-bare-terminate",
]
