name: Android Tests

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android-tests:
    name: Android Tests
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6

      # - name: Enable KVM
      #   run: |
      #     echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
      #     sudo udevadm control --reload-rules
      #     sudo udevadm trigger --name-match=kvm

      # - uses: awalsh128/cache-apt-pkgs-action@latest
      #   with:
      #     packages: libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      #     version: '1.0'

      - uses: ZhongRuoyu/setup-llvm@v0
        with:
          llvm-version: 22

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-linux-android

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: tests/src-tauri

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'tests/package-lock.json'

      - name: Install plugin dependencies
        run: npm ci --ignore-scripts

      - name: Install test app dependencies
        working-directory: tests
        run: npm ci --ignore-scripts

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          ndk: 27.2.12479018
          arch: x86_64
          target: google_apis
          disk-size: 512M
          working-directory: tests
          script: ./test-android.sh
